$(function(){
	//--
	if($('#headDiv').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>100){
				$('.headDiv').addClass('headDiv2');
				}else{
					$('.headDiv').removeClass('headDiv2');
					}
			})
		}
	//--
	$('.jobLayer').find('.list').find('li:last').css('border-bottom','0px');
	if($(".scroll").length>0){
	  $(".scroll").niceScroll({
		  cursorcolor:"#777",
		  cursorborder:"none",
		  cursorwidth:"5px",
		  scrollspeed:80,
		  background:"#AEAEAE",
		  cursoropacitymin:0.5,
		  cursoropacitymax:0.7,
		  mousescrollstep:40,
		  touchbehavior:true
	  });
	}
	$('.jobLayer').find('.scroll:first').fadeIn(200);
	$('.jobLayer').find('.fl').find('a').each(function(i){
		$(this).click(function(){
			$('.jobLayer').find('.fl').find('a').removeClass('aNow');
			$(this).addClass('aNow');
			$('.jobLayer').find('.scroll').hide();
			$('.jobLayer').find('.scroll').eq(i).fadeIn(200);
			})
		})
	$('.job').find('li').each(function(i){
		$(this).click(function(){
			prompt_fun('.jobLayer');
			$('.jobLayer').find('.fl').find('a').removeClass('aNow');
			$('.jobLayer').find('.fl').find('a').eq(i).addClass('aNow');
			$('.jobLayer').find('.scroll').hide();
			$('.jobLayer').find('.scroll').eq(i).fadeIn(200);
			})
		})
	$('.job').find('li').hover(
	   function(){
		   $(this).find('img').stop(true,true).animate({top:-10,height:248},300,'easeOutQuart');
		   },
	   function(){
		   $(this).find('img').stop(true,true).animate({top:0,height:228},300,'easeOutQuart');
		   }
	)
	//--
	$('.aboutPart2').find('li:odd').addClass('liOdd');
	//--
	$('.indexFlash').find('.btn').click(function(){
		$('body,html').stop(true,true).animate({scrollTop:$('.indexPart5').offset().top+240},600,'easeOutQuart');
		})
	//
	})